#! /usr/bin/perl -w
  
use strict;
use Net::PcapUtils;

sub got_a_packet {
    my ( $user_arg, $header, $packet ) = @_;

    print "Got a packet!\n\n" ;
    print "The user argument is: ", $user_arg, "\n";
    print "The header data is: \n";
    foreach my $name (sort keys %{$header})
    {
        print "    $name -> ${$header}{$name}\n";
    }
    print "The packet data is:   ", $packet, "\n";
}

my $status = Net::PcapUtils::loop( \&got_a_packet );
  
if ( $status )
{
    print "Net::PcapUtils::loop returned: $status\n";
}
