#!/bin/bash

### BEGIN INIT INFO
# Provides: liinfo 
# Required-Start: $network
# Required-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Set BGInfo like info on your desktop
### END INIT INFO

/root/bin/liinfo
